services:
  fastapi:
    image: test-template-fastapi-mongodb-auth-image
    build: .
    container_name: test-template-fastapi-mongodb-auth-image
    ports:
      - "8083:8080" # 8083 is the port on the host machine, change it to any port you want
    volumes:
      - .:/code